### ISSUE TITLE
Local file included Unable to run the sample

### ISSUE THREAD

**Issue by meankit1990** [webaddicted/Flutter-Movies4U#1]
Hi..

I tried to run this sample but there is a local file included with path in movie_like.dart class

import 'file:///D:/AndroidStudioProjects/testing/flutter_movie_app/lib/view/likemovie/keepalive_widget.dart';

Can you please update this so that I can try the same. Will help me in learning flutter

Thanks in advance

**Comment by webaddicted** [comment]
Hi,

keepalive_widget is already added but it take path from D drive.
Now I change this and update it.

BR,
Deepak
