### ISSUE TITLE
Remove unused files in git repo

### ISSUE THREAD

**Issue by jinfagang** [webaddicted/Flutter-Movies4U#2]
Dude, did you know your repo is about 400M + which is pretty large for a flutter app source code ??????

**Comment by webaddicted** [comment]
Hi @jinfagang,

I know i just added some video and lots of image in this repo that's why repo is quit heavy. 
I don't want to separate these things files. 

BR, 
Deepak

**Comment by webaddicted** [comment]
Hey @jinfagang,

Now I change path of all heavy file so now repo size is very less. 

Thanks,
Deepak
