### ISSUE TITLE
Dude you said you moved all big files and I clone your repo

### ISSUE THREAD

**Issue by jinfagang** [webaddicted/Flutter-Movies4U#4]
![image](https://user-images.githubusercontent.com/21303438/103540182-4efa6c80-4ed4-11eb-9816-ede2ff232520.png)

Do u know remove file from local not in .git will not effect anyting? Your repo is now more than 1G.... It's a good idea to learn some usage about git

**Comment by webaddicted** [comment]
Hi @jinfagang ,

Thanks for your update.
Can you please help me in how can I remove file from .git.
I try but I can't delete file from .git.
Please update me how can I remove file .

**Comment by jinfagang** [comment]
@webaddicted  using `git rm ...` or try remove all .git folder if you wrongly add too many big files into it. and git init again

**Comment by webaddicted** [comment]
@jinfagang  if I remove all .git folder then my all commit are removed from repository. I don't want to do this this is last option for me.
Can you let me other way.

**Comment by webaddicted** [comment]
@jinfagang  Now repo size reduced.
