### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by JigyassaLamba** [webaddicted/Flutter-Movies4U#5]
I tried to copy and paste some of the code to my project but got a problem with the home screen. The image is attached below. Could you please help me with this error?
@webaddicted 
@sgopal138 

![image](https://user-images.githubusercontent.com/64310774/114061043-9a496000-98b3-11eb-95e1-b77ec2daf727.png)

**Comment by webaddicted** [comment]
Hi, 
@JigyassaLamba did you check internet permission in your project.
Also check and confirm, does original code contain same error.

**Comment by JigyassaLamba** [comment]
Yes, internet is enabled. No, the original one is working. Could you suggest any solution to the above error or share any docs or videos on  how did u integrated API in flutter app?

**Comment by webaddicted** [comment]
you need to check **https://github.com/webaddicted/Flutter-Movies4U/blob/master/lib/utils/apiutils/api_response.dart**
this class while run your API. then you exactly get to know what is exact issue.
